[build-system]
requires = [
    "setuptools>=77", 
    "setuptools_scm>=8.0",
    "numpy>=1.20"
]
build-backend = "setuptools.build_meta"

[project]
name = "pyFCS"
dynamic = ["version", ]
authors = [
    {name="Paul David Harris", email="harripd@gmail.com"}]
description = "Functions for performing auto and cross-correlations of single photon data with and without weights"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]
keywords = ["FCS","single molecule", "correlation", "biophysics", "TCSPC"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering"
 ]
Homepage = "https://github.com/OpenSMFS/pyFCS"
Documentation = "https://pyfcs.readthedocs.io/en/latest/"
Repositories = "https://github.com/OpenSMFS/pyFCS/"
Issues = "https://github.com/OpenSMFS/pyFCS/issues"

requires-python = ">= 3.10"
dependencies = [
    "numpy>=1.20",
]


[tool.setuptools.packages.find]
include = ['pyFCS*']

[tool.setuptools_scm]

[tool.setuptools.package-data]
pyFCS = ["pyFCS"]
